##Spring Configuration
server:
  port: 8080
spring:
  application:
    name: notification
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: /h2
  profiles:
    include:
  rabbitmq:
    host: "chimpanzee.rmq.cloudamqp.com"
    password: "TwvM99SI7FWfsnsC1VXZds9G-yL8DtgS"
    username: "ondiqfmh"
    virtual_host: "ondiqfmh"
  mail:
    host: smtp.gmail.com
    port: 587
    username: esteban.garcia@sofka.com.co
    password: Sofka.2021*
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true